Repository gabrielkarras/SOEN341, pull requests merged in 2022-01, with the labels that each got.

#12 Feat: Added pre-commit hooks and Django template
  .flake8
  .gitignore
  .pre-commit-config.yaml
  README.md
  amazon/amazon/__init__.py
  amazon/amazon/asgi.py
  amazon/amazon/settings.py
  amazon/amazon/urls.py
  amazon/amazon/wsgi.py
  amazon/manage.py
  pyproject.toml
  requirements.txt
Labels: documentation, enhancement

#50 #43 Updated & cleaned up README with our current core features
  README.md
Labels: documentation

#52 Fix #51 : streamlined the installation process and improved documentation
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: bug, documentation
